ITP4887_AY2122_GroupProject

package used
```{r}
require(jsonlite)
require(lubridate)
require(stringr)
```

Data Pre-processing
```{r}
#Q1 Convert JSON to the dataframe
Data1 <- fromJSON(file.choose())
Data1 <- data.frame(Data1)
Data1
```

```{r}
#Q2 transform the day format
Data1$date <- dmy(Data1$date)
Data1
```

```{r}
#Q3 Fill N/A value
Data1[c("price","types","address","latitude"
,"longitude","beds","baths","bath","reception","receptions","bed")][is.na(Data1[c("price","types","address","latitude"
,"longitude","beds","baths","bath","reception","receptions","bed")])] <- 0
Data1
```

```{r}
#Q4 Aggregate the facilities
Data1["TotalBeds"] <- as.numeric(Data1$beds)+as.numeric(Data1$bed)
Data1["TotalBaths"] <- as.numeric(Data1$bath)+as.numeric(Data1$baths)
Data1["TotalReceptions"] <- as.numeric(Data1$reception)+as.numeric(Data1$receptions)
Data1
```

```{r}
#Q5 Extract type 
Data1$FlatType = Data1$types
Data1$FlatType[grep("flat",Data1$types)] = "flat"
Data1$FlatType[grep("Flat",Data1$types)] = "flat"
Data1$FlatType[grep("detached house",Data1$types)] = "detached house"
Data1$FlatType[grep("Detached house",Data1$types)] = "detached house"
Data1$FlatType[grep("terraced house",Data1$types)] = "terraced house"
Data1$FlatType[grep("Terraced house",Data1$types)] = "terraced house"
Data1$FlatType[grep("semi-detached house",Data1$types)] = "semi-detached house"
Data1$FlatType[grep("end terrace house",Data1$types)] = "end terrace house"
Data1$FlatType[grep("property",Data1$types)] = "property"
Data1$FlatType[grep("Property",Data1$types)] = "property"
Data1$FlatType[grep("maisonette",Data1$types)] = "maisonette"
Data1$FlatType[grep("Maisonette",Data1$types)] = "maisonette"
Data1$FlatType[grep("Studio",Data1$types)] = "Studio" 
Data1$FlatType[grep("cottage",Data1$types)] = "cottage"  
Data1$FlatType[grep("bed mews house",Data1$types)] = "bed mews house" 
Data1$FlatType[grep("town house",Data1$types)] = "town house" 
Data1$FlatType[grep("Town house",Data1$types)] = "town house"
Data1$FlatType[grep("bungalow",Data1$types)] = "bungalow" 
Data1$FlatType[grep("penthouse",Data1$types)] = "penthouse" 
Data1$FlatType[grep("Parking/garage",Data1$types)] = "Parking/garage" 
Data1$FlatType[grep("mobile/park",Data1$types)] = "mobile/park" 
Data1$FlatType[grep("houseboat",Data1$types)] = "houseboat" 
Data1$FlatType[grep("shared accommodation",Data1$types)] = "shared accommodation"
Data1$FlatType[grep("Land",Data1$types)] = "land"
Data1$FlatType[grep("Romm",Data1$types)] = "room"
Data1
```

```{r}
#Q6 output to csv
write.csv(Data1, "Project_Housing.csv")
```
